name: "Dev Terraform Workflow"

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main      

permissions:
  id-token: write
  contents: read
  
jobs: 
  terraform-init-plan:
    runs-on: self-hosted
    steps: 
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: f9573d1d-1333-4d75-8e88-d298a34242a1
          tenant-id: 96e40700-6303-4437-a677-c0d7f1f5eb24
          subscription-id: dfad8f6a-4ed1-4448-b795-d396ad2c60db
            
      - name: Terraform fmt
        id: fmt
        run: terraform fmt -check
        continue-on-error: true
        working-directory: env/dev
        
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: env/dev

      - name: Terraform Validate
        id: validate
        run: terraform validate -no-color
        working-directory: env/dev        
      
      - name: Terraform Plan
        id: plan
        run: terraform plan -no-color -input=false
        continue-on-error: true
        working-directory: env/dev   
        
  terraform-apply:    
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs: terraform-init-plan
    environment: dev
    steps:
      - name: Checkout
        uses: actions/checkout@v5.0.0
    
      - name: Azure Login
        uses: Azure/login@v2.3.0
        with:
          client-id: f9573d1d-1333-4d75-8e88-d298a34242a1
          tenant-id: 96e40700-6303-4437-a677-c0d7f1f5eb24
          subscription-id: dfad8f6a-4ed1-4448-b795-d396ad2c60db
          
      - name: Terraform Init
        id: init
        run: terraform init -input=false  
        working-directory: env/dev

      - name: Terraform Apply
        id: apply
        run: terraform apply --auto-approve
        continue-on-error: true
        working-directory: env/dev              
          
